##默认端口
server:
  port: 9092
  servlet:
    session:
      ##默认session有效期
      timeout: 10s
  tomcat:
    max-threads: 0
    ##默认编码
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      ##默认前缀
      prefix: /
      ##默认后缀
#      suffix: .html
   ##关闭thymeleaf缓存
#  thymeleaf:
#    cache: false
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
#    template-loader-path: classpath:/web/
